# Generated by Django 5.0.1 on 2024-01-15 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField(unique=True)),
                ('Email_id', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField(unique=True)),
                ('Email_id', models.CharField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('hospital_name', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doctername', models.CharField(max_length=200)),
                ('Organ_name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(max_length=200)),
                ('bloodgroup', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
                ('idproof', models.FileField(upload_to='')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('Assigned', 'Assigned'), ('pending', 'pending')], default='pending', max_length=200)),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donor')),
                ('hospital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hospital')),
                ('reciver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.receiver')),
            ],
        ),
    ]
