# Generated by Django 5.0.1 on 2024-01-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donor_idproof_donor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='idproof',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='photo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
