# Generated by Django 5.0.1 on 2024-01-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_donor_idproof_alter_donor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='idproof',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='donor',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
